/**
 * corridorBuilder.js — Corridor generation between rooms
 *
 * Responsibilities:
 *  - Connect the rooms generated by MapGenerator
 *  - Ensure all rooms are reachable (connected graph)
 *  - Route corridors that DO NOT cross other rooms
 *  - Return an array of Corridor for the Renderer to draw
 *
 * Structure of a Corridor:
 * {
 *   fromRoomId: number,
 *   toRoomId:   number,
 *   points:     [{x, y}],  // 3 or 4 points (exit -> bends -> entrance)
 *   width:      number,
 * }
 *
 * Exit system per side:
 *  Each room has 4 possible sides: 'right', 'left', 'bottom', 'top'.
 *  Each side is occupied at most ONCE (maximum 4 exits per room).
 *  The preferred side is determined by the relative direction between rooms.
 *
 * Connection algorithm: Kruskal (Minimum Spanning Tree)
 *  1. All edges with weight = Euclidean distance
 *  2. Union-Find to build MST without cycles
 *  3. Optional extra edges (~15%) to create alternative paths
 *
 * Routing with crossing detection:
 *  For each corridor, up to N routing candidates are tested.
 *  The first one that does not cross any room is chosen.
 *  With grid-based placement (mapGenerator), most use the
 *  primary candidate without needing a fallback.
 */

const CorridorBuilder = (() => {

  const CORRIDOR_WIDTH = 16;   // corridor width in pixels
  const HALF_W         = CORRIDOR_WIDTH / 2;

  // ---------------------------------------------------
  // build(rooms)
  // Public entry point.
  //
  // @param {Room[]} rooms  rooms generated by MapGenerator
  // @returns {Corridor[]}
  // ---------------------------------------------------
  function build(rooms) {
    if (rooms.length < 2) return [];

    const allEdges  = _buildGraph(rooms);
    const mstEdges  = _minimumSpanningTree(allEdges, rooms);
    const finalEdges = _addExtraEdges(mstEdges, allEdges);

    // Tracks sides already occupied per room: { roomId -> Set<side> }
    const usedSides = {};
    rooms.forEach(r => { usedSides[r.id] = new Set(); });

    return finalEdges.map(edge => {
      const roomA = rooms.find(r => r.id === edge.fromId);
      const roomB = rooms.find(r => r.id === edge.toId);

      if (!roomA.connections.includes(roomB.id)) roomA.connections.push(roomB.id);
      if (!roomB.connections.includes(roomA.id)) roomB.connections.push(roomA.id);

      // Pass all rooms for crossing verification
      return _buildCorridor(roomA, roomB, usedSides, rooms);
    });
  }

  // ---------------------------------------------------
  // _buildGraph(rooms)
  // Generates all possible edges sorted by ascending distance.
  //
  // @returns {{ fromId, toId, distance }[]}
  // ---------------------------------------------------
  function _buildGraph(rooms) {
    const edges = [];
    for (let i = 0; i < rooms.length; i++) {
      for (let j = i + 1; j < rooms.length; j++) {
        edges.push({
          fromId:   rooms[i].id,
          toId:     rooms[j].id,
          distance: MathUtils.distance(
            MathUtils.rectCenter(rooms[i]),
            MathUtils.rectCenter(rooms[j])
          ),
        });
      }
    }
    edges.sort((a, b) => a.distance - b.distance);
    return edges;
  }

  // ---------------------------------------------------
  // _minimumSpanningTree(edges, rooms)
  // Kruskal with Union-Find — ensures minimum connected graph.
  //
  // @returns {{ fromId, toId }[]}
  // ---------------------------------------------------
  function _minimumSpanningTree(edges, rooms) {
    const parent = {};
    rooms.forEach(r => { parent[r.id] = r.id; });

    function find(id) {
      if (parent[id] !== id) parent[id] = find(parent[id]);
      return parent[id];
    }

    function union(a, b) {
      const ra = find(a), rb = find(b);
      if (ra === rb) return false;
      parent[ra] = rb;
      return true;
    }

    const mst = [];
    edges.forEach(e => { if (union(e.fromId, e.toId)) mst.push(e); });
    return mst;
  }

  // ---------------------------------------------------
  // _addExtraEdges(mstEdges, allEdges)
  // Adds ~15% extra edges to create alternative cycles.
  //
  // @returns {{ fromId, toId }[]}
  // ---------------------------------------------------
  function _addExtraEdges(mstEdges, allEdges) {
    const mstSet = new Set(
      mstEdges.map(e => `${Math.min(e.fromId, e.toId)}-${Math.max(e.fromId, e.toId)}`)
    );

    const extras = allEdges
      .filter(e => !mstSet.has(`${Math.min(e.fromId, e.toId)}-${Math.max(e.fromId, e.toId)}`))
      .filter(() => Random.next() < 0.15);

    return [...mstEdges, ...extras.map(e => ({ fromId: e.fromId, toId: e.toId }))];
  }

  // ---------------------------------------------------
  // _chooseSide(room, targetCenter, usedSides)
  // Chooses which side of `room` to use for the corridor exit,
  // taking into account the relative direction and already occupied sides.
  //
  // Preference order (based on the angle of vector A->B):
  //  B to the right  -> ['right', 'top', 'bottom', 'left']
  //  B to the left   -> ['left',  'top', 'bottom', 'right']
  //  B below         -> ['bottom','right','left',  'top'  ]
  //  B above         -> ['top',   'right','left',  'bottom']
  //
  // @param {Room} room
  // @param {{x,y}} targetCenter
  // @param {object} usedSides  { roomId -> Set<string> }
  // @returns {string}
  // ---------------------------------------------------
  function _chooseSide(room, targetCenter, usedSides) {
    const center = MathUtils.rectCenter(room);
    const dx     = targetCenter.x - center.x;
    const dy     = targetCenter.y - center.y;

    const preferred = Math.abs(dx) >= Math.abs(dy)
      ? (dx >= 0 ? ['right','top','bottom','left'] : ['left','top','bottom','right'])
      : (dy >= 0 ? ['bottom','right','left','top'] : ['top','right','left','bottom']);

    const chosen = preferred.find(s => !usedSides[room.id].has(s)) || preferred[0];
    usedSides[room.id].add(chosen);
    return chosen;
  }

  // ---------------------------------------------------
  // _getExitPoint(room, side)
  // Calculates the point at the center of the chosen edge of the room.
  //
  //   right  -> (x+w,      cy,   axis='h')
  //   left   -> (x,        cy,   axis='h')
  //   bottom -> (cx,       y+h,  axis='v')
  //   top    -> (cx,       y,    axis='v')
  //
  // @returns {{x, y, axis: 'h'|'v'}}
  // ---------------------------------------------------
  function _getExitPoint(room, side) {
    const cx = room.x + room.width  / 2;
    const cy = room.y + room.height / 2;
    switch (side) {
      case 'right':  return { x: room.x + room.width,  y: cy,              axis: 'h' };
      case 'left':   return { x: room.x,               y: cy,              axis: 'h' };
      case 'bottom': return { x: cx,                   y: room.y + room.height, axis: 'v' };
      case 'top':    return { x: cx,                   y: room.y,          axis: 'v' };
    }
  }

  // ---------------------------------------------------
  // _segmentCrossesRoom(p1, p2, room)
  // Checks if the rectilinear segment p1->p2 (horizontal or vertical)
  // crosses the rectangle `room`, considering the corridor thickness.
  //
  // The room rectangle is expanded by HALF_W to simulate thickness.
  //
  // @param {{x,y}} p1
  // @param {{x,y}} p2
  // @param {Room}  room
  // @returns {boolean}
  // ---------------------------------------------------
  function _segmentCrossesRoom(p1, p2, room) {
    // Expand room bounds by half the corridor width
    const rx1 = room.x          - HALF_W;
    const ry1 = room.y          - HALF_W;
    const rx2 = room.x + room.width  + HALF_W;
    const ry2 = room.y + room.height + HALF_W;

    if (p1.y === p2.y) {
      // HORIZONTAL segment at height y = p1.y
      const y  = p1.y;
      const x1 = Math.min(p1.x, p2.x);
      const x2 = Math.max(p1.x, p2.x);
      return (y > ry1 && y < ry2 && x2 > rx1 && x1 < rx2);
    } else {
      // VERTICAL segment at position x = p1.x
      const x  = p1.x;
      const y1 = Math.min(p1.y, p2.y);
      const y2 = Math.max(p1.y, p2.y);
      return (x > rx1 && x < rx2 && y2 > ry1 && y1 < ry2);
    }
  }

  // ---------------------------------------------------
  // _pathIsBlocked(points, rooms)
  // Checks if any segment of the path crosses a room from the list.
  //
  // @param {{x,y}[]} points  consecutive points of the path
  // @param {Room[]}  rooms   rooms to check (already excludes A and B)
  // @returns {boolean}
  // ---------------------------------------------------
  function _pathIsBlocked(points, rooms) {
    for (let i = 0; i < points.length - 1; i++) {
      const p1 = points[i];
      const p2 = points[i + 1];

      // Degenerate segments (same point) are always free
      if (p1.x === p2.x && p1.y === p2.y) continue;

      for (const room of rooms) {
        if (_segmentCrossesRoom(p1, p2, room)) return true;
      }
    }
    return false;
  }

  // ---------------------------------------------------
  // _buildCorridor(roomA, roomB, usedSides, allRooms)
  // Builds the corridor between two rooms by trying routes
  // that do not cross other rooms.
  //
  // Routing logic by axis:
  //
  //  H->H (both lateral):    S-shape with vertical split at midX
  //    candidates: center, near A, near B, outside left, outside right
  //
  //  V->V (both vertical):   S-shape with horizontal split at midY
  //    candidates: center, near A, near B, outside above, outside below
  //
  //  H->V or V->H:           L-shape with elbow at (exitB.x, exitA.y)
  //                           or (exitA.x, exitB.y)                    (2 options)
  //
  // For each candidate, checks crossing with other rooms.
  // Returns the first clean candidate, or the primary as fallback.
  //
  // @param {Room}   roomA
  // @param {Room}   roomB
  // @param {object} usedSides  { roomId -> Set<string> }
  // @param {Room[]} allRooms   used for crossing tests
  // @returns {Corridor}
  // ---------------------------------------------------
  function _buildCorridor(roomA, roomB, usedSides, allRooms) {
    const centerA = MathUtils.rectCenter(roomA);
    const centerB = MathUtils.rectCenter(roomB);

    const sideA = _chooseSide(roomA, centerB, usedSides);
    const sideB = _chooseSide(roomB, centerA, usedSides);

    const exitA = _getExitPoint(roomA, sideA);
    const exitB = _getExitPoint(roomB, sideB);

    // Rooms to check: all except A and B (the corridor MAY touch A and B)
    const others = allRooms.filter(r => r.id !== roomA.id && r.id !== roomB.id);

    // ---- Generate routing candidates ----
    const candidates = [];

    if (exitA.axis === exitB.axis) {
      if (exitA.axis === 'h') {
        // H->H: S-shape, split on the X axis
        // Tests 5 midX values: center, near A, near B, exterior left/right
        const midCenter = (exitA.x + exitB.x) / 2;
        const left  = Math.min(exitA.x, exitB.x) - 80;
        const right = Math.max(exitA.x, exitB.x) + 80;

        [midCenter,
         exitA.x + (exitB.x - exitA.x) * 0.25,
         exitA.x + (exitB.x - exitA.x) * 0.75,
         left,
         right,
        ].forEach(midX => {
          candidates.push([
            { x: exitA.x, y: exitA.y },
            { x: midX,    y: exitA.y },
            { x: midX,    y: exitB.y },
            { x: exitB.x, y: exitB.y },
          ]);
        });

      } else {
        // V->V: S-shape, split on the Y axis
        const midCenter = (exitA.y + exitB.y) / 2;
        const top    = Math.min(exitA.y, exitB.y) - 80;
        const bottom = Math.max(exitA.y, exitB.y) + 80;

        [midCenter,
         exitA.y + (exitB.y - exitA.y) * 0.25,
         exitA.y + (exitB.y - exitA.y) * 0.75,
         top,
         bottom,
        ].forEach(midY => {
          candidates.push([
            { x: exitA.x, y: exitA.y },
            { x: exitA.x, y: midY    },
            { x: exitB.x, y: midY    },
            { x: exitB.x, y: exitB.y },
          ]);
        });
      }

    } else {
      // L-shape: different axes — only 2 possible orientations
      if (exitA.axis === 'h') {
        // A exits horizontally: elbow at (exitB.x, exitA.y)
        candidates.push([
          { x: exitA.x, y: exitA.y },
          { x: exitB.x, y: exitA.y },
          { x: exitB.x, y: exitB.y },
        ]);
        // Alternative: detour through B's Y first (extra bend)
        const midX = (exitA.x + exitB.x) / 2;
        candidates.push([
          { x: exitA.x, y: exitA.y },
          { x: midX,    y: exitA.y },
          { x: midX,    y: exitB.y },
          { x: exitB.x, y: exitB.y },
        ]);
      } else {
        // A exits vertically: elbow at (exitA.x, exitB.y)
        candidates.push([
          { x: exitA.x, y: exitA.y },
          { x: exitA.x, y: exitB.y },
          { x: exitB.x, y: exitB.y },
        ]);
        // Alternative: detour through B's X first (extra bend)
        const midY = (exitA.y + exitB.y) / 2;
        candidates.push([
          { x: exitA.x, y: exitA.y },
          { x: exitA.x, y: midY    },
          { x: exitB.x, y: midY    },
          { x: exitB.x, y: exitB.y },
        ]);
      }
    }

    // ---- Choose the first candidate that does not cross rooms ----
    let chosen = candidates[0]; // fallback: first candidate (never undefined)

    for (const pts of candidates) {
      if (!_pathIsBlocked(pts, others)) {
        chosen = pts;
        break;
      }
    }

    return {
      fromRoomId: roomA.id,
      toRoomId:   roomB.id,
      points:     chosen,
      width:      CORRIDOR_WIDTH,
    };
  }

  // ---------------------------------------------------
  // Public API
  // ---------------------------------------------------
  return { build };

})();
